### ISSUE TITLE
@interface for 'CDVPlugin' declares the selector 'initWithWebView:'

### ISSUE THREAD

**Issue by rrubio** [Wizcorp/phonegap-facebook-plugin#1227]
Hi Guys,

The plugin had been working beautifully up until last night. Getting the following errors on iOS only, android is fine. 

**Error under xcode:**
/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m:27:44: No visible @interface for 'CDVPlugin' declares the selector 'initWithWebView:'

Error under command line (ionic run ios): 

**The following build commands failed:**
    CompileC build/Leezair.build/Debug-iphonesimulator/myProject.build/Objects-normal/i386/FacebookConnectPlugin.o myProject/Plugins/phonegap-facebook-plugin/FacebookConnectPlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Running on:
xcode version 7.2.1
ionic version 1.7.14

**Comment by vcajes** [comment]
Same problem here

**Comment by vcajes** [comment]
Duplicated problem https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1226

**Comment by rrubio** [comment]
Here's another entry about the samething #1222

**Comment by rrubio** [comment]
OK! so possible fix as per #1199 i've installed @jeduan patch (cordova 5) on my mac running cordova 6 and so far it appears to work fine. Says compatibility to cordova 5, but ok on 6 at the moment iOS emulator. Will test in the morning with devices android and iOS. If someone else could also verify this patch works in order to close issue.

A re-write was required. Thanks @jeduan 
https://github.com/jeduan/cordova-plugin-facebook4

**Comment by magnusburton** [comment]
@rrubio I can confirm that this works on Ionic and Cordova 6.0.0. Thank you so much!

**Comment by rrubio** [comment]
:+1:  awesome! i'm about to start testing on my devices and will confirm shortly too.

**Comment by rrubio** [comment]
I can confirm "cordova-plugin-facebook4" works on cordova 6 iOS and Android. This issue should stay open until/if this plugin gets fixed "phonegap-facebook-plugin".

**Comment by maksymilian-majer** [comment]
Guys, this has been fixed in the Telerik fork: https://github.com/Telerik-Verified-Plugins/Facebook

**Comment by aromka** [comment]
yup, the Telerik fork seems to work!

**Comment by rrubio** [comment]
Thank you @maksymilian-majer

**Comment by DipakMahapurkar** [comment]
Hey @rrubio can provide some steps for solve this issue ?
Because i am still face same issue in my ionic framework app.
Thank you

**Comment by murilosardinha** [comment]
same same here!

**Comment by jmvalencia** [comment]
I have installed Telerik plugin and it works too, one question is it stable to keep working with it?

**Comment by crazybaud** [comment]
Workaround with Meteor + Ionic : 
- remove the old one
- `meteor add com.phonegap.plugins.facebookconnect@https://github.com/Telerik-Verified-Plugins/Facebook.git#ae73cc5a1ec125146cf9e4134656db09405c4f2c`

**Comment by sameera207** [comment]
as @maksymilian-majer mentioned Telerik fork: https://github.com/Telerik-Verified-Plugins/Facebook worked for me 

Steps I did

1 - remove the phonegap-facebook-plugin plugin
2 - add the https://github.com/Telerik-Verified-Plugins/Facebook plugin
3 - remove ios/android platforms 
4 - add the platforms again 
5 - win 😄

**Comment by vcajes** [comment]
The solution is quite simple. We've solved the problem by just switching to this repository:

https://github.com/jeduan/cordova-plugin-facebook4

No code changes in your client application.

**Comment by andresarslanian** [comment]
the fix of @sameera207 worked for me.
the one @vcajes proposes works but at least for me (iOS) does not use the native login as the first one does.

hope it helps!

**edit:**
the jeduan version now works with the native login!

**Comment by junerockwell** [comment]
@sameera207 's steps helped out a lot. But build failed when running in Android (`ionic run android` on real device).

If anyone is getting this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.android.support:support-v4:23.2.1.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.2.1/support-v4-23.2.1.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.2.1/support-v4-23.2.1.jar
     Required by:
         :android:unspecified > com.facebook.android:facebook-android-sdk:4.11.0
   > Could not find com.android.support:cardview-v7:23.2.1.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/cardview-v7/23.2.1/cardview-v7-23.2.1.pom
         https://repo1.maven.org/maven2/com/android/support/cardview-v7/23.2.1/cardview-v7-23.2.1.jar
     Required by:
         :android:unspecified > com.facebook.android:facebook-android-sdk:4.11.0
   > Could not find com.android.support:customtabs:23.2.1.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/customtabs/23.2.1/customtabs-23.2.1.pom
         https://repo1.maven.org/maven2/com/android/support/customtabs/23.2.1/customtabs-23.2.1.jar
     Required by:
         :android:unspecified > com.facebook.android:facebook-android-sdk:4.11.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Run your Android SDK Manager and install Android Support Repository revision 32 or higher. I didn't find revision 32 on my SDK Manager so I went a head and installed revision 35.

**Comment by iamntg** [comment]
@sameera207 that worked for me in both android and ios. 
I had error with android build, but was fixed by removing the patch in the build.gradle file which i did for fixing the build error for this plugin.

the code I removed in the build.gradle is

```
configurations {
    all*.exclude group: 'com.android.support', module: 'support-v4'
}
```

that fixes my error in android and works like charm

**Comment by svarughese91** [comment]
I installed "cordova-plugin-facebook4" and moved the "phonegap-facebook-plugin" from the plugin directory of ionic to the lib directory and it worked for me!

**Comment by AppleMonkey** [comment]
You can Solve this in 2 ways:

1- replace [super initWithWebView:theWebView] by [super init].

2- add a compiler flag to FacebookConnectPlugin.m to disable ARC, the compiler flag is -fno-objc-arc

From my point of view, I recommend the second solution because it's not affecting the code.

if you are looking for a step by step solution do the following in Xcode.

Select your main project.
Select your target
Go to build phases
Expand the compiled resources tap
select "CDVFile.m"
at the right side of the "FacebookConnectPlugin.m", you can add the following compiler flag

-fno-objc-arc
Now if you want to understand the problem in details:

The FacebookConnectPlugin was built under non-ARC environment and he controls his memory consumption. but Xcode doesn't allow that as it's using ARC to control the memory consumption of the whole app. so the solution for this conflict is to revamp the FacebookConnectPlugin Code to use ARC or simply tell the Xcode that you are responsible for the memory management of this class by adding the compiler flag.
